# Generated by Django 3.2.1 on 2021-05-16 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0002_rename_name_items_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='description',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='items',
            name='myfile',
            field=models.FileField(editable=False, upload_to=''),
        ),
    ]
